apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
    - port: 11211
      targetPort: vpromc-port # hope this port works
      protocol: TCP
  selector:
    app: vpromc
  type: ClusterIP
