apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 80
      targetPort: vproapp-port # Replace 8080 with the actual port number of your container
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer

