apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 80
      targetPort: 8080 # Replace with the actual port number of your container or use vproapp-port
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer

